### PR TITLE
Crdcdh 2050 

### PR DESCRIPTION
**Pull request by vshand11**
Updated error message.  Please merge the previous PR to 3.1.0 first.

### CODE REVIEW

**Review by n2iw — CHANGES_REQUESTED** [review]
Please use 3.1.0 branch as base branch to create feature branch. Current branch is created based on CRDCDH-2043-0012-pgu, so the PR contains more than what the ticket needs.

**Comment by vshand11** [comment]
> Please use 3.1.0 branch as base branch to create feature branch. Current branch is created based on CRDCDH-2043-0012-pgu, so the PR contains more than what the ticket needs.

After merged previous PR, I will merge 3.1.0 to the branch and you will not see other changes.

**Review by n2iw — APPROVED** [review]
LGTM

**Review by n2iw — CHANGES_REQUESTED** [review]
By creating a new branch based on latest 3.1.0 and merged this branch into it, I tested again and got following errors:
`<14>1 2024-11-20T22:08:56.360Z - - 82735 - - ERROR: (File_Validator) Downloading manifest failed - internal error. Please try again and contact the helpdesk if this error persists.
Traceback (most recent call last):
  File "/Users/yingm3/work/code/data-hub/cli-uploader/src/file_validator.py", line 165, in read_manifest
    result, msg = s3_bucket.check_object_exist(key)
AttributeError: 'S3Bucket' object has no attribute 'check_object_exist'
<14>1 2024-11-20T22:08:56.361Z - - 82735 - - ERROR: (FileLoader) Failed to upload files: found invalid file(s)!
Failed to upload files: found invalid file(s)!  Please check log file in tmp folder for details.`

**Comment by vshand11** [comment]
Updated and works after testing.

**Review by n2iw — APPROVED** [review]
LGTM

**Pull request merged**
